#!/bin/zsh

cat << EOF
* always provide unified diffs for code changes
* retain original code formatting
* retain naming conventions from pasted code for any new names
* limit your line lengths to 80 characters when possible
* for music output, use lilypond format and generate both pdf and midi output
EOF

# vim:ft=vimwiki:
